<?xml version="1.0"?>
<package format="3">
  <name>hand_pipeline</name>
  <version>0.1.0</version>
  <description>ROS2 input, validation, safe targeting, and episode nodes for Hand2Robot.</description>
  <maintainer email="3319676168@qq.com">fery</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>hand2robot_core</exec_depend>
  <exec_depend>hand_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>python3-opencv</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
